# Generated by Django 3.1.7 on 2021-05-01 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210428_2104'),
        ('custumers', '0003_auto_20210315_1859'),
        ('alimentation', '0002_topup_withdrawed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withrdrawed_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('confirmed_by_withdrawer', models.BooleanField(default=False)),
                ('confirmed_by_admin', models.BooleanField(default=False)),
                ('versed_to', models.CharField(max_length=300)),
                ('versed_at', models.DateTimeField()),
                ('amount_by_withdrawer', models.FloatField(blank=True, default=datetime.datetime.now)),
                ('amount_by_admin', models.FloatField(blank=True, null=True)),
                ('note', models.TextField()),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.media')),
                ('topups', models.ManyToManyField(to='alimentation.TopUp')),
                ('withdrawed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirements', to='custumers.manager')),
                ('withdrawed_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements', to='custumers.manager')),
            ],
        ),
    ]
