# Generated by Django 3.1.7 on 2021-03-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0002_auto_20210311_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(blank=True, choices=[('deposit_agent', 'DEPOSIT_AGENT')], max_length=300, null=True),
        ),
    ]
