# Generated by Django 3.1.7 on 2021-03-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0003_auto_20210315_1859'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.PositiveSmallIntegerField(choices=[(0, "MONNEY DIDN'T ARRIVE"), (1, 'Transaction is incomplete'), (2, 'false credentials'), (3, 'to every one')], default=3)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custumers.manager')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
