# Generated by Django 3.1.7 on 2021-04-18 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('note', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('opening_date', models.DateTimeField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='orders.Good'),
        ),
    ]
