# Generated by Django 3.1.7 on 2021-04-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210418_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Media'),
        ),
        migrations.AlterField(
            model_name='good',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='opening_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
