# Generated by Django 3.1.7 on 2021-04-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210420_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='require_manual_activation',
            field=models.BooleanField(default=True),
        ),
    ]
