# Generated by Django 3.1.7 on 2021-04-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210427_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buying_price',
        ),
    ]
