# Generated by Django 3.1.7 on 2021-04-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210427_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(default=[], to='orders.Good'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(-2, 'REQUEST REFUND'), (-1, 'REFUND GRANTED'), (0, 'PRODUCT NEED RESTOCK'), (1, 'AGENT NEEDED FOR ACTIVATION'), (2, 'ORDER  COMPLETED')], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sold_after',
            field=models.FloatField(),
        ),
    ]
