# Generated by Django 3.1.7 on 2021-05-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0003_auto_20210315_1859'),
        ('orders', '0014_auto_20210428_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportPaper',
        ),
    ]
