# Generated by Django 3.1.7 on 2021-06-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210506_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
