# Generated by Django 3.1.7 on 2021-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_lineitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='goods',
            field=models.ManyToManyField(default=[], to='orders.Good'),
        ),
    ]
